# Generated by Django 5.2.5 on 2025-09-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agendamento',
        ),
    ]
