# Generated by Django 5.2.5 on 2025-08-19 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Clínica PneumoSono', max_length=100)),
                ('objetivo_geral', models.TextField()),
                ('secretaria_nome', models.CharField(default='Raro', max_length=100)),
                ('telefone_contato', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
                ('referencia_localizacao', models.CharField(max_length=200)),
                ('politica_agendamento', models.TextField(help_text='Texto sobre a política de horários pré-agendados e possíveis demoras.')),
                ('google_calendar_id', models.CharField(blank=True, help_text='O ID do Google Calendar PRINCIPAL da clínica.', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('o_que_e', models.TextField()),
                ('como_funciona', models.TextField()),
                ('preparacao', models.TextField(blank=True, null=True)),
                ('vantagem', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especialidades', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('convenios', models.CharField(help_text='Ex: Atende apenas CASSI', max_length=200)),
                ('preco_particular', models.DecimalField(decimal_places=2, max_digits=8)),
                ('formas_pagamento', models.CharField(max_length=200)),
                ('retorno_info', models.CharField(default='Consulta de retorno em até 30 dias incluído no valor.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nome', models.CharField(max_length=255)),
                ('paciente_telefone', models.CharField(max_length=20)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado'), ('Realizado', 'Realizado')], default='Pendente', max_length=20)),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chatbot.medico')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_semana', models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (7, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_trabalho', to='chatbot.medico')),
            ],
            options={
                'unique_together': {('medico', 'dia_da_semana', 'hora_inicio')},
            },
        ),
    ]
