# Generated by Django 5.2.5 on 2025-09-01 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinica', '0002_clinicainfo_numero_whatsapp'),
        ('usuarios', '0002_paciente_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('finalizada', 'Finalizada'), ('redirecionada', 'Redirecionada para Secretária')], default='ativa', max_length=20)),
                ('resumo', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='usuarios.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Direcionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitacao', models.CharField(choices=[('agendamento', 'Solicitação de Agendamento'), ('duvida_complexa', 'Dúvida Complexa'), ('solicitacao_humana', 'Pediu Atendimento Humano'), ('informacao_especifica', 'Informação Específica')], max_length=30)),
                ('resumo_conversa', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('resolvido', 'Resolvido')], default='pendente', max_length=20)),
                ('atendida_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.conversa')),
                ('medico_interesse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcionamentos', to='usuarios.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='MensagemConversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente', models.CharField(choices=[('user', 'Usuário'), ('bot', 'Chatbot'), ('system', 'Sistema')], max_length=10)),
                ('conteudo', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('processada', models.BooleanField(default=False)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chatbot.conversa')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='conversa',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ativa')), fields=('paciente',), name='unique_active_conversation_per_patient'),
        ),
        migrations.AddConstraint(
            model_name='direcionamento',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pendente', 'em_andamento'])), fields=('paciente',), name='unique_pending_direcionamento_per_patient'),
        ),
    ]
