# Generated by Django 5.2.5 on 2025-09-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone_whatsapp', models.CharField(max_length=20, unique=True)),
                ('primeiro_contato', models.DateTimeField(auto_now_add=True)),
                ('ultimo_contato', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
