# Generated by Django 5.2.5 on 2025-09-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
