# Generated by Django 5.2.5 on 2025-08-26 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Clínica PneumoSono', max_length=100)),
                ('objetivo_geral', models.TextField()),
                ('secretaria_nome', models.CharField(default='Raro', max_length=100)),
                ('telefone_contato', models.CharField(max_length=20)),
                ('endereco', models.TextField()),
                ('referencia_localizacao', models.CharField(max_length=200)),
                ('politica_agendamento', models.TextField(help_text='Texto sobre a política de horários pré-agendados e possíveis demoras.')),
                ('google_calendar_id', models.CharField(blank=True, help_text='O ID do Google Calendar PRINCIPAL da clínica.', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição da especialidade', null=True)),
                ('ativa', models.BooleanField(default=True, help_text='Se a especialidade está ativa para seleção')),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('o_que_e', models.TextField()),
                ('como_funciona', models.TextField()),
                ('preparacao', models.TextField(blank=True, null=True)),
                ('vantagem', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('convenios', models.CharField(help_text='Ex: Atende apenas CASSI', max_length=200)),
                ('preco_particular', models.DecimalField(decimal_places=2, max_digits=8)),
                ('formas_pagamento', models.CharField(max_length=200)),
                ('retorno_info', models.CharField(default='Consulta de retorno em até 30 dias incluído no valor.', max_length=100)),
                ('especialidades', models.ManyToManyField(help_text='Selecione uma ou mais especialidades do médico', related_name='medicos', to='clinica.especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_semana', models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (7, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_trabalho', to='clinica.medico')),
            ],
            options={
                'unique_together': {('medico', 'dia_da_semana', 'hora_inicio')},
            },
        ),
    ]
