# Generated by Django 5.2.5 on 2025-08-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicainfo',
            name='numero_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
